### PR TITLE
ADAPT-4415 | @rebeccahongsf | create sb protected page-type

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- create sb protected page
**Note:** I branched off of Nathan's work in PR #277 so I could use the AuthorizationProvider

# Review By (Date)
- when possible please :D

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Run `netlify dev` locally and navigate to `/test/rebecca/tsgg-protected-page/`
3. You should be redirect to the UAT login page. Login as `zguan`.
4. After login, you should be redirect to `/test/rebecca/tsgg-protected-page/` and see the following page: 
image

5. Review code and see if anything smells or is missing 🤔 

# Associated Issues and/or People
- ADAPT-4415

### CODE REVIEW

**Comment by sherakama** [comment]
Thanks @rebeccahongsf. This is looking good. After having looked at the designs that Bhavika we might have a few more feature requests but this is a good home for it.

**Comment by sherakama** [comment]
https://deploy-preview-287--stanford-alumni.netlify.app/test/rebecca/tsgg-protected-page

Deploy preview is 404'ing

Not sure why yet. Could be similar to the other issue we were seeing before.

**Comment by rebeccahongsf** [comment]
> https://deploy-preview-287--stanford-alumni.netlify.app/test/rebecca/tsgg-protected-page
> 
> Deploy preview is 404'ing
> 
> Not sure why yet. Could be similar to the other issue we were seeing before.

This issue does not seem to be caused by the netlify.toml issue we had previously encountered. Perhaps we have a rule that redirects test pages? It seems like the link works if the Storyblok api key is included. I'll keep poking around 🕵️

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
GTG. Merge when ready.

**Pull request merged**
