### PR TITLE
ADAPT-2183 ADAPT-2065 ADAPT-2180 ADAPT-2134: Use Tailwind v2.1, global & local footer, CTA Link, Social Icon

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- This is branched off of #6 
- Swap out the @tailwindcss/jit with Tailwind core version 2.1.1

Copied over #6 summary:
- Add React FontAwesome (only the brand icons) for social media icons
- Add custom text underline styles as TW components
- Add global footer, local footer, navItem, linkGroup, CTA Link, Social Icon components
- An SVG logo file is added to /static/images (used in local footer)
- Note: this works locally, but styles don't show up properly on Netlify build.
- Note2: need to fix the custom link TW style we created (probably due to TW JIT mode) - global footer hover/focus link is wonky.

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Pull this branch, remove package-lock.json and cache, `nvm use`, `npm install`, `npm run build` (run an initial build to generate the TW classes - I find the build command more reliable in doing that), `npm run develop`
2. in the SAA Alumni storyblok space, go to http://app.storyblok.com/#!/me/spaces/103430/stories/0/0/43744022
3. Look at the CTA links (in the WYSIWYG and local footer)
4. Look at the local footer at all breakpoints (to preview changes with selecting different options in Storyblok you'll need to go directly to the local footer in the Global Components folder otherwise the changes won't show up till you save)
5. Look at the code

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
Bad news - still broken on Netlify 👎🏼   Good news - TW v.2.1 works 👍🏼 !

**Comment by yvonnetangsu** [comment]
@sherakama I can probably close #6 and please just review this one instead of #6 since TW v2.1 is working - I'll leave it up for now so you could see my comments there.

**Comment by yvonnetangsu** [comment]
@sherakama I merged this into my branch, and it looks like the global footer styles are a bit wonky - somehow the non responsive classes (eg, `su-flex-col`) generated are overriding the classes with breakpoint prefix (e.g., `sm:su-flex-row`) in the global.css. I remember the global footer looking ok in your branch preview previously though 🤔 
https://deploy-preview-8--stanford-alumni.netlify.app/test/yvonne/test-interior-page/

**Comment by sherakama** [comment]
That probably has to do with me trying to restore the development flow and Webpack's HMR. With the commit that worked I had removed all CSS compilation from the gatsby/webpack build and moved it to the post step. That would have made development tough. I can see now that it isn't good to have a mix of the two. Perhaps there is some way to separate out when the development environment can build the css and when production does the post build tailwind thing.

**Comment by yvonnetangsu** [comment]
@sherakama Think this one could get merged before it gets larger? I expect some continuous tweaks to TW build and what not, but hoping to get this stuff into main branch so it's a little cleaner to review other PRs that branch off from this one 😂

**Comment by sherakama** [comment]
Works for me. I owe you a post-build plugin but that will take some time to create. Keep em roll'n

**Review by sherakama — APPROVED** [review]
Ok

**Comment by yvonnetangsu** [comment]
Yay thanks, Shea!

**Pull request merged**
