### PR TITLE
NOJIRA | @rebeccahongsf | resolve missing hero gradient

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- Resolve missing hero gradient on Notify Me page
- Remove spaces from TripId to account for content authoring error
- Adjust mobile payment styling

# Review By (Date)
- asap

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to [Notify Me page](https://deploy-preview-494--stanford-alumni.netlify.app/travel-study/destinations/italy-test/notify/) and confirm the gradient is appearing
(Compared to PROD example: [Notify Me form](https://alumni.stanford.edu/travel-study/destinations/japan-2023/notify))
3. Review code

# Associated Issues and/or People
- ADAPTTS-233
- ADAPTTS-232

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@rebeccahongsf The gradient update looks good to me. Do you need me to verify the other changes (payment button/trip id)? 😄

**Comment by rebeccahongsf** [comment]
> @rebeccahongsf The gradient update looks good to me. Do you need me to verify the other changes (payment button/trip id)? 😄

Oh yes! Apologies for not updating the instructions sooner @yvonnetangsu  😃 

For Trip Id:
1. Navigate to [`travel-study/destinations/italy-test/register`](https://deploy-preview-494--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register)
2. On the form, confirm that the room categories displays like so:

Option: To test the payment button (this may not show up if you do not have a card payment saved)
3. Continue to the payment summary. If the Saved Payment button displays, confirm that it is styled with the primary button style (like the `Next`) button.

**Comment by yvonnetangsu** [comment]
> > @rebeccahongsf The gradient update looks good to me. Do you need me to verify the other changes (payment button/trip id)? 😄
> 
> Oh yes! Apologies for not updating the instructions sooner @yvonnetangsu 😃
> 
> For Trip Id:
> 
> 1. Navigate to [`travel-study/destinations/italy-test/register`](https://deploy-preview-494--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register)
> 2. On the form, confirm that the room categories displays options

Screen Shot 2022-10-17 at 3 58 31 PM

Like these?

**Comment by rebeccahongsf** [comment]
> > > @rebeccahongsf The gradient update looks good to me. Do you need me to verify the other changes (payment button/trip id)? 😄
> > 
> > 
> > Oh yes! Apologies for not updating the instructions sooner @yvonnetangsu 😃
> > For Trip Id:
> > 
> > 1. Navigate to [`travel-study/destinations/italy-test/register`](https://deploy-preview-494--stanford-alumni.netlify.app/travel-study/destinations/italy-test/register)
> > 2. On the form, confirm that the room categories displays options
> 
> Screen Shot 2022-10-17 at 3 58 31 PM
> 
> Like these?

Eggactly! 😎 (Sorry I just changed the Storyblok trip id since it shares an Id with another trip which is why the categories are showing dupes).

**Review by yvonnetangsu — APPROVED** [review]
GTG - I'll take your word for the 3rd one 😄 👀

**Pull request merged**
