### PR TITLE
ADAPT-5570 ADAPT-5571: Redirects for Alumni Center & Events

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Adds catch all domain redirect for alumni center 

# Review
- Review code for syntax
- Trust the rest

### CODE REVIEW

**Review by rebeccahongsf — APPROVED** [review]
LGTM 👀 Ship it!

**Comment by yvonnetangsu** [comment]
> LGTM 👀 Ship it!

You so fast! 🚀

**Comment by rebeccahongsf** [comment]
> > LGTM 👀 Ship it!
> 
> You so fast! 🚀

I was lurking around 😂 👀

**Comment by yvonnetangsu** [comment]
> > > LGTM 👀 Ship it!
> > 
> > 
> > You so fast! 🚀
> 
> I was lurking around 😂 👀

Very sus 👀

**Comment by rebeccahongsf** [comment]
> > > > LGTM 👀 Ship it!
> > > 
> > > 
> > > You so fast! 🚀
> > 
> > 
> > I was lurking around 😂 👀
> 
> Very sus 👀

[Indeed](https://www.youtube.com/watch?v=vzebQ0jSTC0) 👀

**Comment by sherakama** [comment]
Haha! You both fell for the trap. Snuck in [897b23d](https://github.com/SU-SWS/saa_alumni/pull/647/commits/897b23db159dc7df2be4f7b0dc30b404ac18efff)

**Comment by yvonnetangsu** [comment]
> Haha! You both fell for the trap. Snuck in [897b23d](https://github.com/SU-SWS/saa_alumni/pull/647/commits/897b23db159dc7df2be4f7b0dc30b404ac18efff)

👀 Wow I shall use this trick next time to get my bitcoin miner in

**Comment by rebeccahongsf** [comment]
> > Haha! You both fell for the trap. Snuck in [897b23d](https://github.com/SU-SWS/saa_alumni/pull/647/commits/897b23db159dc7df2be4f7b0dc30b404ac18efff)
> 
> 👀 Wow I shall use this trick next time to get my bitcoin miner in

Ah ha! I had my eye on this PR the entire time and saw the changes 👁️

**Pull request merged**
