### PR TITLE
Release: V.3.0.3-rc.1

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary

- fixup dob DATE offset
- ADAPTSSS-707: Add associate redirect (#545)
- ADAPTTS-251 | @rebeccahongsf | hide deposit header (#548)
- nojira | @rebeccahongsf | update confirmation message tally table sty… 
- ADAPT-5509: Redirect careers.alumni.stanford.edu (#558)
- @rebeccahongsf | update internal trip pre-extension data and… 
- ADAPT-5539: Protect against content references in create blocks. 

# Review By (Date)
- Soonish

# Criticality
5/10

# Notes
- Releases are broken and I will look at them at a later date. That is why the RC.1

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama Something going on that makes the GitHub actions fail?

**Comment by rebeccahongsf** [comment]
@sherakama any chance we could squeeze in the DOB fix from PR #569 ?

**Comment by sherakama** [comment]
> @sherakama any chance we could squeeze in the DOB fix from PR #569 ?

Sure, I could use the commit to trigger a build anyhow

**Comment by sherakama** [comment]
@yvonnetangsu & @rebeccahongsf Green lights! Please one last sanity check.

**Review by yvonnetangsu — APPROVED** [review]
I see that the WSOF fix is in 👍🏼  Will count on @rebeccahongsf to review that all the GG stuff she wants is in 😄

**Pull request merged**
