### PR TITLE
Release: v2.0.6

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- Release the scroll bug and security fix to PROD

# Review By (Date)
- asap

# Associated Issues and/or People
- ADAPT-5438

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
The release looks good @rebeccahongsf but looks like there's some issues with the GitHub action 👀

**Comment by rebeccahongsf** [comment]
> The release looks good @rebeccahongsf but looks like there's some issues with the GitHub action 👀

ronswanson

**Comment by yvonnetangsu** [comment]
> 

Haha eslint being strict? 😬

**Review by yvonnetangsu — APPROVED** [review]
Quick! Merge before it breaks 🤣 
GTG - retested the preview and looked good. Thanks @rebeccahongsf  👍🏼

**Comment by sherakama** [comment]
LOL you two

**Pull request merged**
