### PR TITLE
Release v3.0.3

### PR DESCRIPTION
**Pull request by sherakama**
# Release V3.0.3

# Summary
- ADAPTSSS-707: Add associate redirect

### CODE REVIEW

**Comment by sherakama** [comment]
@rebeccahongsf & @yvonnetangsu 

I did not include the DOB +1 fix for TS in this release.

**Comment by sherakama** [comment]
Waiting for green lights and then going for it.

**Comment by sherakama** [comment]
hmm: Errors in release workflow https://github.com/SU-SWS/saa_alumni/actions/runs/3876868017

Add that to the backlog of things to fix.

**Comment by yvonnetangsu** [comment]
Hmmm weird. Thanks @sherakama for the release!

**Pull request merged**
