### PR TITLE
ADAPT-5588: Sierra Camp redirects.

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- Adds redirects for retiring Sierra camp

# Review By
- End of sprint (Robocop)

# Criticality
- Low

# Review Tasks

1. Review code. 
2. Trust.

### CODE REVIEW

**Comment by sherakama** [comment]
The build failed due to the regular /tmp cache issue we've been seeing. I've rebuilt successfully but the GitHub integration status hasn't changed.

**Comment by yvonnetangsu** [comment]
> The build failed due to the regular /tmp cache issue we've been seeing. I've rebuilt successfully but the GitHub integration status hasn't changed.

Yeah I've seen the same thing happening myself 👍🏼

**Review by yvonnetangsu — APPROVED** [review]
Looks legit - thank you @sherakama 🎉 😄

**Comment by sherakama** [comment]
@yvonnetangsu please include this in your release with the events widget today.

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu please include this in your release with the events widget today.

Yup yup, that's my plan 👍🏼

**Pull request merged**
