### PR TITLE
ADAPT-4469: Payment form theming

### PR DESCRIPTION
**Pull request by Lyafel**
# Summary
- Give gab forms theming

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to https://deploy-preview-321--stanford-alumni.netlify.app/travel-study/additional-payment-form/
2. Review code

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by Lyafel** [comment]
@rebeccahongsf Just making sure I understand correctly, the new design is to be applied to all the forms with some differences between the 3 specific ones that have tickets dedicated to them?

Do we have any control over the forms? There is much that's different from the design. Or how close should they resemble the design?

@bhavikasolanki ^ , also are there designs for the error messages? and should the focus outline stay as it is?

**Comment by rebeccahongsf** [comment]
Great questions @Lyafel! 

Yes, the new design is to be applied to all the forms since all forms will have the same styles for the form field types. We had created tickets for each form (Additional Payment, Custom Journeys, and Notify Me) to primarily review and confirm that the global form styles are being correctly applied across all forms (since some forms use radio buttons while others do not). 

We do not have control over the forms since they are an embed provided by GiveGab. Since we are unable to specify the order of the help text from the form, some of the help text will need to be reordered using CSS to match the order shown in the design instead. And the help text itself might differ from the design at the moment. Aside from the help text, were there other portions of the form that would be difficult to style (or did you have any additional questions about the help text)? Feel free to let me know if additional clarification is needed! 😎 

I pinged Bhavika about the error message designs and will follow up shortly with more information.

Thank you for your patience and all your work on this in the meantime, Elena! 😃

**Comment by rebeccahongsf** [comment]
Following up on the error message design 😄  We should use the Input Error styles from Decanter with a couple of modifications:
- The red outline should use `Digital Red Light Light` (Hex code: #F83535)
- Similar to the help text, links within error text (and icon) should be white by default, Digital Red Light Light and underline on hover. Links should be followed by either an internal or external icon based on the link type. At this time we are not sure if links will be included in the error messages but just in case 😄 
image

- The pink/red background wrapping the label, error text, and text field can be removed/set to transparent.

image
[Direct Link to Decanter's Error Input Design](https://www.figma.com/file/Kmd4utmJFPRMVeCFEEBQhLtx/Decanter-Design-System?node-id=10694%3A292)

Please let me know if I overlooked any information or if you have any other questions! Thanks again, @Lyafel  :D

**Comment by Lyafel** [comment]
@rebeccahongsf this pr includes all but the thank you page, the designs for that one don't seem to be ready.

**Comment by rebeccahongsf** [comment]
Thank you @Lyafel! 😄 I plan to do a review with @bhavikasolanki on Friday so we might have additional feedback then. As of right now, everything is looking good to me. 

**Note:** I did revert the `netlify.toml` file since it sources from a different StoryBlok space (e.g. DEV - SAA Alumni TSGG)

**Review by sherakama — APPROVED** [review]
@rebeccahongsf this looks fine to me to merge into the tsgg branch. A new PR can be created for future updates.

**Pull request merged**
