### PR TITLE
ADAPT-2296: Initial try at a post build plugin.

### PR DESCRIPTION
**Pull request by sherakama**
# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama I seem to have some issues with the local footer (when it's a "story" referenced in another component) after merging in the editor PR from last Friday. This is me running `netlify dev` on the /test/yvonne/test-interior-page. Same if I do `npm run develop`.

Screen Shot 2021-04-19 at 1 07 40 PM

**Comment by yvonnetangsu** [comment]
A little more info - looks like it's not just because of the story references. If I open the "Home" page on storyblok, it doesn't like it if I try to change any of the options, eg, pick a different image focus for the hero, or toggle on the smaller font size checkbox for the headline

Screen Shot 2021-04-19 at 1 27 32 PM

**Comment by sherakama** [comment]
Ok, at this point the production builds are working well but `gatsby develop` is not. With no files to scan in the `public` directory for purge I was hoping to get enough coverage from just including the file itself in the webpack entry points but that seems to not be working 100% as the css file is watched but doesn't render when a component changes.

**Comment by sherakama** [comment]
@yvonnetangsu 

Oooooo kay... So I've beat my head and read all the documentation I could find so far and have only been able to get halfway there. The production build looks great as the JIT compiler can look at the built HTML in the public directory as well as the source code for all the CSS classes and generate the appropriate output. 

See: https://deploy-preview-14--stanford-alumni.netlify.app/

However, `gatsby develop` does not work as I cannot find a way to scan, look, or source the rendered HTML before it is shipped to the browser. I tried the various API methods from Gatsby (Node && SSR) to looking at modifying the webpack and HMR settings. I think we are going to have to go with fixing the source code to have the values rendered. We could perhaps generate a safelist.txt file in decanter-react...

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu
> 
> Oooooo kay... So I've beat my head and read all the documentation I could find so far and have only been able to get halfway there. The production build looks great as the JIT compiler can look at the built HTML in the public directory as well as the source code for all the CSS classes and generate the appropriate output.
> 
> See: https://deploy-preview-14--stanford-alumni.netlify.app/
> 
> However, `gatsby develop` does not work as I cannot find a way to scan, look, or source the rendered HTML before it is shipped to the browser. I tried the various API methods from Gatsby (Node && SSR) to looking at modifying the webpack and HMR settings. I think we are going to have to go with fixing the source code to have the values rendered. We could perhaps generate a safelist.txt file in decanter-react...

Oh nice! Thank you for working on this - I'm so happy that it's building. If it comes to worst, is it possible to have one repo for develop and one for build? (I'm totally not knowledgeable about this kind of stuff so don't judge me if it's ridiculous 😂 )

**Comment by sherakama** [comment]
> Oh nice! Thank you for working on this - I'm so happy that it's building. If it comes to worst, is it possible to have one repo for develop and one for build? (I'm totally not knowledgeable about this kind of stuff so don't judge me if it's ridiculous 😂 )

I'll catch you up in the dev meeting today and we can talk about what to do going forward.

**Pull request closed without merging**
