### PR TITLE
Release/v4.5.0

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #844 

# Review By (Date)
- EOD July 23

# Criticality
- 5

# Review Tasks

## Setup tasks and/or behavior to test

1. See #844

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@shc314 Release is prepped - have the image gallery component been added to PROD storyblok?

**Comment by shc314** [comment]
> @shc314 Release is prepped - have the image gallery component been added to PROD storyblok?

@yvonnetangsu Yes

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
Thank you both.

**Comment by yvonnetangsu** [comment]
Thanks @sherakama! Merging now @shc314

**Comment by yvonnetangsu** [comment]
@shc314 @willyumfrancis 
The image gallery is now in PROD:
https://github.com/SU-SWS/saa_alumni/releases/tag/4.5.0

**Comment by shc314** [comment]
Thank you @yvonnetangsu !

**Pull request merged**
