### PR TITLE
ADAPT-2675, ADAPT-2675, ADAPT-2676: Indexing for Youtube, Soundcloud, and iTunes content. 

### PR DESCRIPTION
**Pull request by nplowman**
# READY FOR REVIEW

# Summary
- Adds Netlify Serverless function that will fetch items from Stanford Alumni's iTunes, Youtube, and Soundcloud catalogs and submit them to a Algolia Search Index

# Review By (Date)
- Before the end of the sprint.

# Criticality
- 4/10 - I believe this was a "nice to have" feature for the federated search on the Alumni site. 

# Review Tasks

## Setup tasks and/or behavior to test

1. Take a look at https://www.algolia.com/apps/IC2GX4TRIN/explorer/browse/alumni_media to view the indexed search results.
2. The function can be triggered on the preview environment at /api/indexMedia. (Expectation is that this will be triggered by a cron job and/or during the Netlify build)

## Front End Validation
N/A - No frontend work is involved in this PR.

### Code
- [x] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/ADAPT-2674
- https://stanfordits.atlassian.net/browse/ADAPT-2675
- https://stanfordits.atlassian.net/browse/ADAPT-2676

### CODE REVIEW

**Comment by nplowman** [comment]
@sherakama 
Just noticed while I was opening this PR that Soundcloud was only getting my the first 10 results, which isn't going to work.
But Youtube and iTunes should still be ready, if you want to review those.

One open question I did have was whether or not we should add some kind of protection to the serverless function, so it doesn't get triggered accidentally/maliciously.

**Comment by sherakama** [comment]
> @sherakama
> Just noticed while I was opening this PR that Soundcloud was only getting my the first 10 results, which isn't going to work.
> But Youtube and iTunes should still be ready, if you want to review those.

I saw your note in the Jira ticket about the RSS feed. It looks like Dena is going to help see if she can get that going for us.

> One open question I did have was whether or not we should add some kind of protection to the serverless function, so it doesn't get triggered accidentally/maliciously.

As indexing operations do equal real $$$ I would prefer that this endpoint have at least a token of some sort to prevent anyone from triggering it.

**Review by sherakama — APPROVED** [review]
This looks GTG. Please add a token string key check to the execution of this function and then it is GTG. Dena is checking in on the Soundcloud RSS feeds but we can refactor when those come to be.

**Comment by nplowman** [comment]
@sherakama I just implemented some basic protection by requiring a secret key to be passed in as a parameter. This is checked against a matching environment variable value.

**Comment by sherakama** [comment]
Thanks for this @nplowman 

This looks good for now. I'll merge it into the main branch and revisions and updates can come later.

**Pull request merged**
