### PR TITLE
Release v4.3.4

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #780 

# Review By (Date)
- EOD Dec 15

# Criticality
- 6

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at code diff

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
The preview actually builds ok
https://deploy-preview-781--stanford-alumni.netlify.app/privacy/

**Comment by yvonnetangsu** [comment]
@sherakama Is this good to go? Kristin said ready to push to PROD 😄

**Review by sherakama — APPROVED** [review]
GTG

**Comment by yvonnetangsu** [comment]
Thanks @sherakama! 😄

**Pull request merged**
