### PR TITLE
ADAPT-3259: Itinerary component

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- Note: Needs to merge main into dev first (but I can't seem to do that directly - says it's protected)
- Add Itinerary component https://stanfordits.atlassian.net/browse/ADAPT-3259
- Add initial set of icons into the Travel Icons dataSource - can add more later depending on client/designer request.
Screen Shot 2021-09-03 at 12 15 08 AM

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- 5/10

# Review Tasks

## Setup tasks and/or behavior to test

1. https://deploy-preview-150--stanford-alumni-uat.netlify.app/test/yvonne/test-itinerary/
2. Scroll to the Itinerary section. Check that it matches the mockup
Screen Shot 2021-09-01 at 5 14 06 PM
3. Pull down locally, nvm use, npm run develop, Go to the Test Itinerary Storyblok page and try editing the itinerary. Confirm that everything is working as intended.
http://app.storyblok.com/#!/me/spaces/118608/stories/0/0/69410253
3. Go to https://deploy-preview-150--stanford-alumni-uat.netlify.app/events/
4. Check that the dates on the event cards and all variants still look the same as before.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/ADAPT-3259
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama @mattanglin Do we have a process to keep the main and dev branch in sync? Or do I just manually merge main into dev?

**Comment by mattanglin** [comment]
> @sherakama @mattanglin Do we have a process to keep the main and dev branch in sync? Or do I just manually merge main into dev?

@yvonnetangsu Just saw this. This repo doesn't currently have automation to keep main/dev in sync yet. Until the pipeline automation is in place we'll have to manually do it on release (merge `release/branch` to `main`). I just updated `dev` so it should be in sync with `main` currently (still ahead a bit).

**Review by mattanglin — APPROVED** [review]
Itinerary looks great! 👍🏼

**Comment by yvonnetangsu** [comment]
> Itinerary looks great! 👍🏼

Awesome. Thanks for the review, @mattanglin! This branch has some stuff that's branched off of `main` (which is ahead of `dev`) - is that an issue if I merge this PR into `dev`? I tried to merge `main` into `dev`, but it won't allow me to push to origin (says it's a protected branch).

**Pull request merged**
