### PR TITLE
Release v4.4.2

### PR DESCRIPTION
**Pull request by ericbakenhus**
Release v4.4.2

Includes:
- events-discovery merge action: #854 
- Webhook background function: #851 
- Mega Menu option to sub pages on Alumni Homesite: #853

### CODE REVIEW

**Review by stfurkan — APPROVED** [review]
@ericbakenhus LGTM! I'm assuming you made all the necessary changes for the production env :)

**Comment by stfurkan** [comment]
@ericbakenhus is it ok for you if I add #853 to this release PR?

**Comment by ericbakenhus** [comment]
> @ericbakenhus is it ok for you if I add #853 to this release PR?

Go for it. 👍

**Comment by ericbakenhus** [comment]
> > > @ericbakenhus is it ok for you if I add #853 to this release PR?
> > 
> > 
> > Go for it. 👍
> 
> Thank you :) I merged `dev` to this branch. It now has the #853

Awesome. I'll merge on green. 🎉

**Pull request merged**
