### PR TITLE
Release/v4.3.13

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #815 
- Please use with caution (color contrast, accessibility)

# Review By (Date)
- end of the week

# Criticality
- 3

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at the preview and make sure the homepage looks ok
2. See comments in #815

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
FYI @William-Misiaszek @shc314

**Comment by shc314** [comment]
@sherakama PR[#826](https://github.com/SU-SWS/saa_alumni/pull/826) is an update to what was in PR[#815](https://github.com/SU-SWS/saa_alumni/pull/815) based on @yvonnetangsu's suggestions. Thank you.

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
@yvonnetangsu @shc314 @William-Misiaszek 

Approved and shipping to production.

**Comment by yvonnetangsu** [comment]
Thank you @sherakama ! I know @shc314 is working on an update PR but that's more of a nice to have, so we can cut another release after that's done 😄

**Pull request merged**
