### PR TITLE
Release v2.0.5

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- Exclude forms from site map
- Update radio button styles
- Protect against missing body value
- Remove deposits from registration types
- Resolve scroll bug on Windows 10/11 Chrome

# Review By (Date)
- asap

# Associated Issues and/or People
- ADAPT-5440 
- ADAPT-5438
- ADAPT-5439
- ADAPT-5410
- ADAPT-5426
- ADAPT-5318

### CODE REVIEW

**Comment by sherakama** [comment]
This one worked: https://deploy-preview-481--stanford-alumni.netlify.app/

**Review by sherakama — APPROVED** [review]
Ok.

**Comment by rebeccahongsf** [comment]
> @ericbakenhus

Any tips on how one might rerun the Netlify tests? I do not have permissions to merge unless all checks are gtg 🤔 

I recall previously that if we redeployed through Netlify, it would update the statuses here but I'm not sure what has changed since then.

**Comment by sherakama** [comment]
It got detached somehow. Triggered a small edit to fix it.

**Comment by yvonnetangsu** [comment]
@rebeccahongsf @sherakama I've had the same issue with GitHub action being detached if Netlify deploys are manually redeployed on Giving too 🤔

**Pull request merged**
