### PR TITLE
V 3.0.1

### PR DESCRIPTION
**Pull request by sherakama**
# Release 3.0.1

Testing 1... 2... 3.0.1

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
🤞🏼 😬

**Comment by sherakama** [comment]
🤦 Forgot the label...

**Comment by sherakama** [comment]
But it worked 🤔 

https://github.com/SU-SWS/saa_alumni/releases/tag/3.0.1

**Comment by yvonnetangsu** [comment]
Am glad it worked 😹 🎉

**Pull request merged**
