### PR TITLE
Release/v2.0.3

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- additional info coming soon

# Review By (Date)
- this morning 

# Review Tasks

## Setup tasks and/or behavior to test

1. Review code

### CODE REVIEW

**Comment by rebeccahongsf** [comment]
Ack! Looks like I might've merged instead of squashed and merged one of the PRs 💀 Will fix that

**Comment by sherakama** [comment]
We want the same commit history in the main branch as the dev branch. If the dev branch has all of those commits then you will have to clean it up there first.

I think the path of least resistance will be to have a messy commit history here.

**Comment by rebeccahongsf** [comment]
Biting the bullet with the merge history. Let's ship it as it 🥳

**Review by yvonnetangsu — APPROVED** [review]
LGTM Rebecca! 🎉 😄

**Pull request merged**
