### PR TITLE
ADAPT-2880: Search Modal open/close behavior

### PR DESCRIPTION
**Pull request by nplowman**
# READY FOR REVIEW

# Summary
This is the first part of the search modal implementation it:
- Adds open/close functionality on the Search button in the header. 
- Provides a modal component with accessibility considerations, like close-on-escape, auto-focus on search input, and focus-trapping.

# Review By (Date)
- Preferably 1-2 days, as other tickets this sprint will build on the work in this PR.

# Criticality
- How critical is this PR on a 1-10 scale?
7/10 - This is a fairly critical piece of functionality for the site, that appears on the sitewide header. 

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Go to any page that has the sitewide header added. (For example: http://localhost:8000/test/yvonne/test-dark-page)
3. Click the "Search" button in the header. 
4. Confirm that the modal is opened.
5. Confirm that focus trap works as expected.
6. Confirm that accessibility features, like close-on-escape work as expected.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/ADAPT-2280

### CODE REVIEW

**Comment by nplowman** [comment]
Oh - worth noting this branch is based on the search branch, which has yet to be merged.
Ideally, PR #38 should be merged first. 

If that is not feasible, I can probably rebase this branch off of main, as I have not wired in any of the search functionality yet that depends on that branch.

**Review by sherakama — COMMENTED** [review]
The new items in this look great. @nplowman How about changing the destination branch to `search` and merging it down to there?

**Review by sherakama — APPROVED** [review]
GTG to 'search' branch.

**Comment by nplowman** [comment]
@sherakama Sounds good - merging this into search.

**Pull request merged**
