### PR TITLE
ADAPT-2223: Storyblok Editor V1 Updates

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Fixes issues with editor.js

# Review By (Date)
- Whenever

# Criticality
- Med/Low

# Review Tasks

## Setup tasks and/or behavior to test

1. Check this branch out on your local and start a server (netlify dev or gatsby develop)
2. Fire up the editor in the storyblok UI 
3. Visit a page
4. Test out the different features and make sure they all work.

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama This is definitely better - I could change out the options on fields mostly with no issues. I'm only having issues with 2 things - 1) with the global component picker, e.g., the Local Footer Picker. Try going to my test-interior-page and toggle the selected local footer on and off. 2) If I switch a CTA link from internal link to URL

http://app.storyblok.com/#!/me/spaces/103430/stories/0/0/43744022

I'll get this pop up error. Once you save, it's all there and the error goes away.

Screen Shot 2021-04-20 at 11 06 46 PM

Another very minor issue is that, I see a flash of "add this to component.js" message when I refresh.

I wonder if we want to wait a bit till Storyblok catch up with Gatsby 3 to upgrade to Gatsby 3?

**Comment by sherakama** [comment]
> I wonder if we want to wait a bit till Storyblok catch up with Gatsby 3 to upgrade to Gatsby 3?

You quit too soon. I should have resolved that flash of missing component messaging and have resolved the relation resolving issue. Please re-try.

**Comment by yvonnetangsu** [comment]
> > I wonder if we want to wait a bit till Storyblok catch up with Gatsby 3 to upgrade to Gatsby 3?
> 
> You quit too soon. I should have resolved that flash of missing component messaging and have resolved the relation resolving issue. Please re-try.

😂 😂

**Review by yvonnetangsu — APPROVED** [review]
Yay - works well! GTG. Thanks!

**Pull request merged**
