### PR TITLE
Release/v4.3.5

### PR DESCRIPTION
**Pull request by yvonnetangsu**
# READY FOR REVIEW

# Summary
- #710 
- #757 

# Review By (Date)
- Jan 5 EOD

# Criticality
- 6

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at code diff and preview

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
Looks like I included the #757 as well - are we ready to push that to PROD @sherakama @shc314 ?

**Comment by sherakama** [comment]
https://github.com/SU-SWS/saa_alumni/pull/786/commits/5fd94eb08b40ac0a7a5a1a1bd78beb0e5f3288fb#diff-77a39ffe850878142d005b6c30e507c6dd0c5263720ad90c3915c78fe41eb8bdR37

This line might be an issue as the `gradientProp` property from the block will always be undefined and that might cause an issue as you cannot have an index of undefined in the `heroGradient` object but it is likely just a warning.

**Comment by yvonnetangsu** [comment]
> [5fd94eb#diff-77a39ffe850878142d005b6c30e507c6dd0c5263720ad90c3915c78fe41eb8bdR37](https://github.com/SU-SWS/saa_alumni/commit/5fd94eb08b40ac0a7a5a1a1bd78beb0e5f3288fb#diff-77a39ffe850878142d005b6c30e507c6dd0c5263720ad90c3915c78fe41eb8bdR37)
> 
> This line might be an issue as the `gradientProp` property from the block will always be undefined and that might cause an issue as you cannot have an index of undefined in the `heroGradient` object but it is likely just a warning.

Hmm good point @sherakama. I did test the new hero gradient options that @shc314 added on PROD, but didn't encounter any breaking errors. What do you think we push this release live first (since it fixes some of the bigger visual regression issues), and then @shc314 can make any updates later?

**Comment by sherakama** [comment]
@yvonnetangsu, please go ahead with the release.

Thank you @shc314 for adding the fields to the bloks.

**Review by sherakama — APPROVED** [review]

**Comment by yvonnetangsu** [comment]
Thank you @shc314 and @sherakama ! Have a great weekend 👋🏼 😄

**Pull request merged**
