### PR TITLE
NO-JIRA: Add UNIX time to Algolia for Sync Events

### PR DESCRIPTION
**Pull request by stfurkan**
# READY FOR REVIEW

# Summary
- Add UNIX start - end times to Algolia for sync events

# Review By (Date)
- ASAP

# Criticality
- 5

# Review Tasks

## Setup tasks and/or behavior to test

1. I temporarily setup the env variables for the PR #857 in Netlify. You can test the function changes using it.

I'll remove the temp configs after we merge this to `dev`

### CODE REVIEW

**Comment by stfurkan** [comment]
@ericbakenhus @sherakama we need UNIX time in Algolia records to be able to use the time fields in filters.

**Comment by ericbakenhus** [comment]
@stfurkan I'm configuring the sort for the replica as part of DS-687. It's currently set to sort by the `startTimestamp` field. The code for that is in #858. I do see now that it makes more sense to merge it to dev though. I can pull DS-687 related work out of that PR.

**Comment by stfurkan** [comment]
> @stfurkan I'm configuring the sort for the replica as part of [DS-687](https://stanford.atlassian.net/browse/DS-687). It's currently set to sort by the `startTimestamp` field. The code for that is in #858. I do see now that it makes more sense to merge it to dev though. I can pull [DS-687](https://stanford.atlassian.net/browse/DS-687) related work out of that PR.

Thanks @ericbakenhus :) If we can merge at least the unix timestamps to dev, it'll be great. It's currently a blocker for the date filters.

In #858, we are going to store the unix timestamp in second (not millisecond) right?

https://github.com/SU-SWS/saa_alumni/blob/ca24cfd782b432a309a4b46a86bf7573871c9094/src/utilities/synchronizedEvents.js#L67-L69

**Comment by ericbakenhus** [comment]
> > @stfurkan I'm configuring the sort for the replica as part of [DS-687](https://stanford.atlassian.net/browse/DS-687). It's currently set to sort by the `startTimestamp` field. The code for that is in #858. I do see now that it makes more sense to merge it to dev though. I can pull [DS-687](https://stanford.atlassian.net/browse/DS-687) related work out of that PR.
> 
> Thanks @ericbakenhus :) If we can merge at least the unix timestamps to dev, it'll be great. It's currently a blocker for the date filters.
> 
> In #858, we are going to store the unix timestamp in second (not millisecond) right?
> 
> https://github.com/SU-SWS/saa_alumni/blob/ca24cfd782b432a309a4b46a86bf7573871c9094/src/utilities/synchronizedEvents.js#L67-L69

Yep! Luxon's `toUnixInteger()` returns seconds. 👍

**Comment by stfurkan** [comment]
> > > @stfurkan I'm configuring the sort for the replica as part of [DS-687](https://stanford.atlassian.net/browse/DS-687). It's currently set to sort by the `startTimestamp` field. The code for that is in #858. I do see now that it makes more sense to merge it to dev though. I can pull [DS-687](https://stanford.atlassian.net/browse/DS-687) related work out of that PR.
> > 
> > 
> > Thanks @ericbakenhus :) If we can merge at least the unix timestamps to dev, it'll be great. It's currently a blocker for the date filters.
> > In #858, we are going to store the unix timestamp in second (not millisecond) right?
> > https://github.com/SU-SWS/saa_alumni/blob/ca24cfd782b432a309a4b46a86bf7573871c9094/src/utilities/synchronizedEvents.js#L67-L69
> 
> Yep! Luxon's `toUnixInteger()` returns seconds. 👍

Perfect :) Thanks @ericbakenhus. I'm closing this PR and will wait for your PR for this change.

**Pull request closed without merging**
