### PR TITLE
Release: v5.2.0

### PR DESCRIPTION
**Pull request by sherakama**
# Release: v5.2.0

# Summary
-  DS-734: Add alumni events to federated search (#936)

### CODE REVIEW

**Comment by sherakama** [comment]
The Algolia crawler work has been merged and deployed to production. Once this is in place, I'll make the Algolia application adjustments and run the crawler.

**Comment by sherakama** [comment]
Site does build. Just the normal cache clear was required: https://deploy-preview-995--stanford-alumni.netlify.app/search

**Comment by ericbakenhus** [comment]
@sherakama Does that failing search test need an eventual update or is it just being flaky?

**Review by ericbakenhus — APPROVED** [review]
👍

**Comment by sherakama** [comment]
> @sherakama Does that failing search test need an eventual update or is it just being flaky?

Hmm no. That is a new one. I had the tests running green in the original PR. I'll look into this one.

**Comment by sherakama** [comment]
https://deploy-preview-995--stanford-alumni.netlify.app/search/?q=lorem%20ipsum

There is a test event 🤦

**Pull request merged**
