### PR TITLE
ADAPTSM-189 | @rebeccahongsf | fixup installment payment review tally table

### PR DESCRIPTION
**Pull request by rebeccahongsf**
# READY FOR REVIEW

# Summary
- fixup installment payment review tally table

# Review By (Date)
- asap

# Review Tasks

## Setup tasks and/or behavior to test

1. Navigate to `/membership/register`
2. Select Myself > Installment
3. Fill out first page of form and navigate to payment page
4. Verify that the installment payment review section appears like so: 
image

5. Navigate back to `/membership/register`
6. Test out Myself > Full payment
7. Fill out first page of form and navigate to payment page
8. Verify that the existing tally table styles has not been impacted by these changes
9. Review code 🪴 

# Associated Issues and/or People
- ADAPTSM-189

### CODE REVIEW

**Comment by rebeccahongsf** [comment]
@jdwjdwjdw  feel free to retro review when you have the chance! I'm going to roll this in so membership can also QA as well😄

**Review by jdwjdwjdw — COMMENTED** [review]
@rebeccahongsf haha was just about to comment. Installments page looking good. Non-installments payment review section could probably use a slight adjustment - it would be nice if `Total` lined up with the total amount, and I'm assuming you may want to remove the border underneath the total like you did for installments.
Screen Shot 2023-05-15 at 3 41 23 PM

**Comment by rebeccahongsf** [comment]
> @rebeccahongsf haha was just about to comment. Installments page looking good. Non-installments payment review section could probably use a slight adjustment - it would be nice if `Total` lined up with the total amount, and I'm assuming you may want to remove the border underneath the total like you did for installments. Screen Shot 2023-05-15 at 3 41 23 PM

Thanks for the retro review, @jdwjdwjdw 😄 I pushed a fix to the membership branch, do you mind taking a look and retesting on https://membership--stanford-alumni.netlify.app/membership/register when you have the chance?

**Comment by jdwjdwjdw** [comment]
@rebeccahongsf thanks! Underline is gone, but it looks like it's getting hit with a padding-bottom outside of the `su-pb-0` you added, so the numbers still aren't lining up
Screen Shot 2023-05-16 at 12 04 16 PM

**Comment by jdwjdwjdw** [comment]
@rebeccahongsf looking good now 😎

**Pull request merged**
