### PR TITLE
ADAPT-5091: Check if is authentificated before showing the user button

### PR DESCRIPTION
**Pull request by Lyafel**
# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by sherakama** [comment]
@Lyafel This looks great. Thank you.

Can I ask one scope creepy addition? Can you add a loading skeleton about the same size as the words `log in` while it is being processed to help mitigate against the layout shift that happens? 

eg: https://www.npmjs.com/package/react-loading-skeleton

**Comment by Lyafel** [comment]
@sherakama Added a placeholder element, though an empty one. Let me know if that doesn't work. Maybe a little spinner in it? 
Tried to add a package but it doesn't make sense for this one little item, and it looks pretty out of place in this context.

**Comment by sherakama** [comment]
@yvonnetangsu 

What do you think about the gap of space and the layout shift in the header while the login is processing? Do we bother worrying about it or is it enough that we should put some sort of loading indicator in there?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu
> 
> What do you think about the gap of space and the layout shift in the header while the login is processing? Do we bother worrying about it or is it enough that we should put some sort of loading indicator in there?

@sherakama 
Hmmmmmm for me the horizontal shift doesn't bother me, but the vertical shift is more obvious.
if possible perhaps we could put a placeholder element in there that is the same height as the login state (the circle avatar), that would probably help a bit.

Also, not directly related to this, but the login state mobile breakpoint looks a bit off currently 🤔 @Lyafel 
Screen Shot 2022-07-21 at 2 30 24 PM

**Comment by Lyafel** [comment]
@yvonnetangsu did we have a design for logged in mobile? Can't find it

**Comment by sherakama** [comment]
@Lyafel Ok, here is what we'll do. Please put a spinner (https://www.davidhu.io/react-spinners/storybook/index.html?path=/docs/moonloader--main) into the space that the logged in user's avatar would take up while it is loading. We don't have a design for this so let's use white as the loading SVG color. 

Thanks.

**Comment by yvonnetangsu** [comment]
@Lyafel This is what I meant - just adding some spacing above and below the circle (or the placeholder while it's authenticating) Thanks!
Screen Shot 2022-07-26 at 2 26 06 PM

**Review by sherakama — APPROVED** [review]
LG2M, @yvonnetangsu this looks fine to me for the current state. I am in the process of creating tickets for the next state. Please also have a review.

**Review by yvonnetangsu — APPROVED** [review]
Looks great - thanks @Lyafel !

**Pull request merged**
