### PR TITLE
ADAPT-3834: Manual story card

### PR DESCRIPTION
**Pull request by Lyafel**
# Summary
- Created a story card that can be populated manually instead of pulling content from stories 

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by Lyafel** [comment]
@yvonnetangsu I added a test card on the front page for testing (called New Card Title)

**Review by yvonnetangsu — CHANGES_REQUESTED** [review]
@Lyafel Is it possible to create a reusable story card component that is then used by storyCard and saaStoryCard? 🤔  Looks like storyCardManual has same code as 
https://github.com/SU-SWS/saa_alumni/blob/dev/src/components/content-types/story/storyCardView.js

**Comment by Lyafel** [comment]
@yvonnetangsu You're right! I got so confused in how to that I didn't see the simple solution.

**Review by yvonnetangsu — CHANGES_REQUESTED** [review]
@Lyafel Thanks for the revision but I think this needs a bit more work. Currently, some of the fields on the saaStoryCard isn't working because those values from Storyblok aren't being passed to StoryCardView, e.g., the isBigText, headingLevel, hideTab options.

I think you could create a reusable card similar to the component `GradientCard`. The `GradientCard` is then used by the collectionCard.js (under storyblok/cards/, this would be like our saaStoryCard where author manually create each card) as well as perkCardView.js (this would be like our storyCardView.js in which the perkCard content is pulled from a published Perk content type).

**Comment by Lyafel** [comment]
@yvonnetangsu Good point, didn't check for those fields. Should be working now

**Review by yvonnetangsu — CHANGES_REQUESTED** [review]
@Lyafel This is working well! The only thing I see missing from the Storyblok manual card is the storyType field - I imagine the content authors would be able to pick the same story types (in the Story content type on Storyblok), and the corresponding icons will show in the manual card title. After that should be GTG. Thanks!

**Comment by Lyafel** [comment]
@yvonnetangsu Field was added, please check

**Review by yvonnetangsu — APPROVED** [review]
Thanks for adding the story type, @Lyafel ! Working great for me. GTG. @sherakama when we cut a release for this, we'll add this component to the Storyblok PROD site 😄

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
@yvonnetangsu to Squash and Merge when ready.

**Comment by yvonnetangsu** [comment]
Merging into dev - we'll coordinate for a release to production, @sherakama 😃

**Pull request merged**
