### PR TITLE
DS-766 | @ericbakenhus | Magazine redirects

### PR DESCRIPTION
**Pull request by ericbakenhus**
# READY FOR REVIEW

# Summary
- Adds some magazine redirects

# Review By (Date)
- End of sprint (or before 7/12)

# Criticality
- Low

# Review Tasks

## Setup tasks and/or behavior to test

1. Look at redirects
2. Make sure they redirect on the deploy preview

# Associated Issues and/or People
- DS-766

### CODE REVIEW

**Comment by sherakama** [comment]
I see you've run into Netlify's lack of documentation for this format
If you're looking for examples try this out for size https://github.com/SU-SWS/ood_online_giving/blob/dev/static/_redirects

**Comment by sherakama** [comment]
Redirects will execute on the first match so put your most specific redirects at the top of the document.

**Comment by ericbakenhus** [comment]
> Redirects will execute on the first match so put your most specific redirects at the top of the document.

They gave me two redirects with the same source URL, so I'm just waiting for a fix there. Everything else should be good to go. 👍

**Review by sherakama — APPROVED** [review]
GTG after redirect for article_id 88299 is sorted out.

**Pull request merged**
