### PR TITLE
Delete merge-to-stage.yml

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- We're not using a staging environment any longer are we?

### CODE REVIEW

**Comment by yvonnetangsu** [comment]
@sherakama It was initially for T/S, but maybe we're done with staging? @rebeccahongsf might have more up-to-date info.

**Comment by sherakama** [comment]
@rebeccahongsf ?

**Comment by rebeccahongsf** [comment]
To be completely transparent, I did not know this existed @sherakama @yvonnetangsu 
I'll follow up with T/S and see if they are still actively using the staging site.

**Comment by rebeccahongsf** [comment]
We got the green light to retire staging 👍 @sherakama @yvonnetangsu

**Review by rebeccahongsf — APPROVED** [review]

**Comment by yvonnetangsu** [comment]
> We got the green light to retire staging 👍 @sherakama @yvonnetangsu

Thanks for confirming @rebeccahongsf ! 😄 🚀

**Pull request merged**
