### PR TITLE
ADAPT-3115: Refactored facets implementation to allow for multiple values.

### PR DESCRIPTION
**Pull request by nplowman**
# READY FOR REVIEW

# Summary
- Refactors implementation of Search facets to allow for selecting multiple values.
- This may also fix ADAPT-3116

# Review By (Date)
- By end of next week (August 13th). 

# Criticality
- How critical is this PR on a 1-10 scale? 
Probably around a 7-8. 

# Review Tasks

## Setup tasks and/or behavior to test

1. Just visit /search in the preview environment, and test out the new filter behaviors.

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/ADAPT-3115
- https://stanfordits.atlassian.net/browse/ADAPT-3116

# Notes on Implementation
The primary challenge is that after you update the search filters, the updated response from Algolia will remove all of the facet values except for the ones you selected. 
However, Algolia does show the multiple-select behavior in some of their demos, so I was able to do a little bit of reverse engineering to see how this was implemented.
It looks like for "disjunctive facets', which is the name they use for this behavior, they run multiple queries. One for the main search results, plus separate queries for each disjunctive facet.

When you use their Instant Search widgets, it does all of this for you under the hood. But you have to implement this yourself when using the API directly.

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
Code looks solid. Waiting on UX review.

**Review by yvonnetangsu — APPROVED** [review]
Nice - UX looks good to me!

**Comment by sherakama** [comment]
@nplowman Please resolve merge conflict then this is GTG.

**Comment by yvonnetangsu** [comment]
@nplowman Kerri has approved the UX for this. We can merge after fixing the merge conflict. Thank you - this is nice 🎉

**Comment by nplowman** [comment]
@sherakama Conflicts have been resolved.

**Comment by sherakama** [comment]
Ty.

**Pull request merged**
