### PR TITLE
ADAPT-2839: Remove headlessUi transition and set children to static

### PR DESCRIPTION
**Pull request by Lyafel**
# NOT READY FOR REVIEW
- (Edit the above to reflect status)

# Summary
- TL;DR - what's this PR for?

# Review By (Date)
- When does this need to be reviewed by?

# Criticality
- How critical is this PR on a 1-10 scale? Also see [Severity Assessment](https://stanfordits.atlassian.net/browse/D8CORE-1705).
- E.g., it affects one site, or every site and product?

# Review Tasks

## Setup tasks and/or behavior to test

1. Check out this branch
2. Navigate to...
3. Verify...

## Front End Validation
- [ ] Is the markup using the appropriate semantic tags and passes HTML validation?
- [ ] Cross-browser testing has been performed?
- [ ] Automated accessibility scans performed?
- [ ] Manual accessibility tests performed?
- [ ] Design is approved by @ user?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by Lyafel** [comment]
@yvonnetangsu Not sure if removing the transition is an acceptable solution but I managed to make it work with removing transition and setting the Panel to static. Is that fine?

**Comment by yvonnetangsu** [comment]
> @yvonnetangsu Not sure if removing the transition is an acceptable solution but I managed to make it work with removing transition and setting the Panel to static. Is that fine?

Oh great! Yeah, I think not having the transition is fine. However, I did find that with this change, when you use the keyboard to navigate and as you tab from link to link inside an expanded dropdown menu, it doesn't automatically close when you tab away from the last link within (currently the dropdown close as you tab away from the last link item in a dropdown). If you could find a way to fix that, that'd be great.

**Comment by sherakama** [comment]
Screen Shot 2021-07-05 at 11 34 02 PM

I think removing the transition is fine but the keyboard navigation and the collapsing when moving to different menu items still needs to happen.

**Comment by Lyafel** [comment]
Right, missed this. I played with it a bit more and couldn't find a way to fix both things at the same time. probably makes sense to go with the second option and remove the library in this case @yvonnetangsu ?

**Comment by yvonnetangsu** [comment]
> Right, missed this. I played with it a bit more and couldn't find a way to fix both things at the same time. probably makes sense to go with the second option and remove the library in this case @yvonnetangsu ?

Thanks for testing, @Lyafel !

@sherakama What to you think? I remember you mentioned that the clicking twice to close issue isn't that critical and we'll just keep headlessUI (and perhaps the TW team will come up with a solution). If not, we can take it out in August since that counts as a bug fix and isn't a new feature.

**Comment by sherakama** [comment]
I just tried to reproduce the issue again and can only get the double click to close to happen on Safari now. Let's lean on Tailwind's headless UI team to address it at this point. We have some time before go-live to wait and see.

**Comment by yvonnetangsu** [comment]
> I just tried to reproduce the issue again and can only get the double click to close to happen on Safari now. Let's lean on Tailwind's headless UI team to address it at this point. We have some time before go-live to wait and see.

Sounds good to me. Let's leave it as is for now then.

**Pull request closed without merging**
